In [1]:
import numpy as np

In [35]:
transition = np.array([[0.05, 0.1, 0.15, 0.7],
                       [0.1, 0.05, 0.25, 0.6],
                       [0.45, 0.15, 0.05, 0.35],
                       [0.35, 0.2, 0.15, 0.3]])

start = np.array([0.1, 0.4, 0.2, 0.3])

emission = np.array([[0.4, 0.2, 0.1, 0.2, 0.1],
                     [0.3, 0.1, 0.4, 0.1, 0.1],
                     [0.1, 0.1, 0.1, 0.2, 0.5],
                     [0.1, 0.4, 0.1, 0.3, 0.1]])

In [118]:
def convert(word):
    # i stands for the position of a character in a word
    i = 0
    delta = np.zeros([4, len(word)])
    origin = np.zeros([4, len(word)-1])

    for letter in word:
        # j stands for an english letter
        for j in range(4):
            if i==0:
                delta[j,i] = emission[j, letter]*start[j]
            else:
                m = np.argmax(transition[:,j]*delta[:,i-1])
                delta[j,i] = emission[j, letter] * transition[m, j] * delta[m,i-1]
                origin[j,i-1] = m
        i+=1
    
    return delta, origin

In [119]:
word = [2, 1] # 0 = alpha, 1 = tau, 2 = eta, 3 = gamma, 4 = omega

delta, origin = convert(word)
print(delta)
print(origin)

[[0.01   0.0032]
 [0.16   0.0008]
 [0.02   0.004 ]
 [0.03   0.0384]]
[[1.]
 [1.]
 [1.]
 [1.]]


In [122]:
word = [3, 0, 4] # 0 = alpha, 1 = tau, 2 = eta, 3 = gamma, 4 = omega

delta, origin = convert(word)
print(delta)
print(origin)

[[2.00e-02 1.26e-02 9.45e-05]
 [4.00e-02 5.40e-03 1.26e-04]
 [4.00e-02 1.35e-03 9.45e-04]
 [9.00e-02 2.70e-03 8.82e-04]]
[[3. 3.]
 [3. 0.]
 [3. 0.]
 [3. 0.]]


In [121]:
word = [4, 0, 3, 1] # 0 = alpha, 1 = tau, 2 = eta, 3 = gamma, 4 = omega

delta, origin = convert(word)
print(delta)
print(origin)

[[1.000e-02 1.800e-02 2.450e-04 2.646e-04]
 [4.000e-02 4.500e-03 1.800e-04 7.560e-05]
 [1.000e-01 1.000e-03 5.400e-04 5.670e-05]
 [3.000e-02 3.500e-03 3.780e-03 4.536e-04]]
[[2. 3. 3.]
 [2. 0. 3.]
 [1. 0. 3.]
 [2. 0. 3.]]
